name: flutter_chat
description: A Flutter+Firebase Chat App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase Libraries
  firebase_core: "^1.10.0"
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0
  firebase_storage: ^10.1.0
  firebase_messaging: ^11.1.0

  image_picker: ^0.8.4+4
  path: ^1.8.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/defaultProfilePic.png
